/*
 * This source file was generated by the Gradle 'init' task
 */
package pmd;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting()); //NOPMD - suppressed SystemPrintln - suppress violation for current line
        System.out.println("Hello, world !");
    }
}
