version: '3.7'

services:
  database:
    image: postgres:13-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./create-schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
