server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: monitoring

management:
  server:
    port: 8090
  endpoints:
    web:
      base-path: /monitoring
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      show-details: always
      sensitive: false